- Dockerfile
- README.md
- action.yml
- package.json
Improves action speed since it won't need to run `npm ci` every time action runs
> feat: use image from docker hub

- package-lock.json
- package.json
The plugin containing rules to be used by `commitlint-config-jira` was missing from the `package.json`.  This means that when extending `['jira']` in the `commitlint.config.js` it was always failing due to unknown rules.
This fixes #13 and allows easy usage of the `commitlint-config-jira`.
> Added plugin with jira rules for `commitlint-config-jira`

- run.js
This PR enables to pass `opts` param to lint API.
related `@commitlint/cli`'s code: https://github.com/conventional-changelog/commitlint/blob/75cef4e8f74e180cf4c601afde295f2c35336b58/%40commitlint/cli/src/cli.js#L152
> feat: support lint opts

- run.js
"before" field already shows the commit before the push event was sent, so we can use it as "from" field of the revision.
Fixes #18
> fix: do not try to get parent of push event's "before" field

- .github/workflows/ci.yml
- .github/workflows/commitlint.yml
- README.md
Related issue: https://github.com/wagoid/commitlint-github-action/issues/21
> docs: update usage to explain how to use it with actions/checkout@v2

- README.md
- action.js
- action.test.js
- action.yml
This follows the commitlint CLI behavior, which exits with success when there are only warnings.
This behavior can be changed by passing 'true' to the parameter `failOnWarnings`.
Fixes #25
> fix: don't fail on warnings

- src/action.js
- src/action.test.js
> fix: action shows error ouput when not all commits have warnings

- README.md
- action.yml
- src/action.js
- src/action.test.js
When no configFile is given and the `commitlint.config.js` file doesn't exist in the repository, then no config is loaded at all.
This PR brings in the `config-conventional` as default config when the config file does not exist.
> feat: use config-conventional as default config

- package-lock.json
- package.json
- src/action.js
The commit message is printed, which may contain workflow commands. See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
> fix: do not run workflow commands in commit messages

- README.md
`set-env` is deprecated and disabled as of November 16th, 2020 as mentioned on the GitHub blog: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
> docs: use `env` to replace deprecated `set-env` in example

- .github/workflows/ci.yml
Due to security reasons, ::set-env command doesn't work anymore. The new method of
updating env vars dynamically is through the $GITHUB_ENV file.
> ci: replace set-env calls with $GITHUB_ENV file

- .lintstagedrc.js
- package-lock.json
- package.json
`pretty-quick` is not needed any more as lint-staged can run prettier with just the staged files, thus getting the same behaviour.
Closes #60.
> test: run tests before committing, in addition to `pretty-quick`

- README.md
- src/action.js
- src/action.test.js
- src/generateOutputs.js
Related to https://github.com/wagoid/commitlint-github-action/issues/70
> feat: add command execution again

- .github/workflows/ci.yml
- .github/workflows/commitlint.yml
- Dockerfile
`npm ci` is meant to be used in CI environments and the scripts are ignored to prevent e.g. Husky
from being installed in the CI environment. See https://docs.npmjs.com/cli/v7/commands/npm-ci.
> ci: run `npm ci` to install and ignore scripts

- .github/workflows/ci.yml
This avoids the following error:
"Updates were rejected because the tip of your current branch is behind its remote counterpart"
This happens when a PR is merged while release is in progress.
> fix: perform an atomic push when releasing

- README.md
> docs: resolve ambiguities

- .dockerignore
- CHANGELOG.md
- README.md
- action.yml
- src/action.test.js
Related to https://github.com/wagoid/commitlint-github-action/issues/194
> fix: default to .cjs extension in config files

- .github/workflows/ci.yml
This PR adds specific permissions to the existing ci.yml workflow under .github/workflows.
I am the founder of [Step Security](https://www.stepsecurity.io), and have implemented a [GitHub App](https://github.com/apps/step-security) to automatically restrict permissions for the GITHUB_TOKEN in workflows. This is a security best practice as per the GitHub Actions [hardening guide](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions). 
I am trying the App out on important public repositories, by forking them, installing the App on the fork, and manually creating PRs with the fixed workflows. The App automatically fixes permissions when a new PR is created that changes  a workflow, so feel free to install it for future workflows, or try it out on …
> Add specific permissions to workflows under .github/workflows

- README.md
- entrypoint.sh
Related to https://github.com/actions/checkout/issues/760
`actions/checkout` already fixed the issue on their side in
[v3.0.1](https://github.com/actions/checkout/releases/tag/v3.0.1).
But since this is a container action, it can be run with another uid than the one
from `actions/checkout` and therefore we need to add the `safe.directory` config again.
Another way of fixing this would be to make this action run with the same uid as the github runner, but as mentioned [here](https://github.com/actions/checkout/issues/760#issuecomment-1098135955) we're not sure whether the `1000` uid of the runner is reliable.
The different `uid` issue seems more like a Github Actions ecosystem problem, maybe they'll take care of it later.
> ci: set workspace directory as safe after checkout

- Dockerfile
- package-lock.json
- package.json
According to Snyk.io, the currently used base Docker image has 19 security
vulnerabilities (13 high).
https://snyk.io/test/docker/node%3A16.5.0-alpine3.14
On the other hand, the image `node:16.14.2-alpine3.14` has no known security
vulnerabilies.
https://snyk.io/test/docker/node%3A16.14.2-alpine3.14
This commit upgrades the image to fix the above mentioned issues.
> build: upgrade base Docker image to prevent security vulnerability

- README.md
- action.yml
- src/action.js
- src/action.test.js
* adds a new optional commitDepth parameter. 
When set to a valid Integer value - X, considers only the latest X number of commits.
This stems from a discussion around https://github.com/wagoid/commitlint-github-action/issues/363
> feat: adds commitDepth as new input param

- README.md
- action.yml
- src/action.js
- src/action.test.js
WIP, trying to implement a flag to the action such that the action will result in a success status regardless of errors or warnings. 
I need to implement one or two tests still, I'm pretty new to developing in TS outside of the AWS CDK so taking my time to learn.
> feat(action): adds flag to optionally fail on errors

- action.yml
- src/action.js
- src/action.test.js
I was hitting an issue with the action reporting:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'You have commit messages with errors
```
I looked into it and the setOutput() call was formatted wrong. I actually read through the action code again and realized the `generateOutputs.js` file was already setting that `results` output so my call to the core function was unnecessary. I removed it and updated the tests accordingly.
> fix(action): removed unnecessary setOutput call

- package-lock.json
- package.json
This fixes #760 properly, without breaking changes. We'll upgrade commitlint to v19 in a major change to the version.
> fix: upgrade commitlint to latest v18

- src/action.mjs
- src/action.test.mjs
- src/testUtils.mjs
To actually resolve https://github.com/wagoid/commitlint-github-action/issues/752. 
This logic uses the `before` and `after` shas in the push event with the [compareCommits](https://octokit.github.io/rest.js/v21/#repos-compare-commits) REST resource in OctoKit to get a list of commits between two shas. This should accomplish getting the commits included from an incoming push to a given `ref`
> fix: using compareCommits for push event commit query

- README.md
- action.yml
- src/action.mjs
- src/action.test.mjs
- src/testUtils.mjs
This pull request adds support for GitHub's merge queue functionality by handling the `merge_group` event in the `commitlint-github-action`. It enables users who utilize GitHub's merge queue feature to lint commit messages effectively during the merge process.
Resolve #744 #757
1. Update `action.mjs` and tests to Support `merge_group` Event:
- Added logic to detect when the action is triggered by a `merge_group` event.
- Updated the way commits are retrieved in this context to ensure the correct commits are linted.
- Verified that the correct commits are being linted in this context.
2. Update README
- Added a new section on using the action with GitHub Merge Queues:
- Provided examples of workflows that listen to the `merge_group` event.
- Explained necessary configurations and …
> feat: handle merge_group event - get squashed commit
